import Vue from 'vue'
import Router from 'vue-router'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _99a7bef8 = () => interopDefault(import('..\\layouts\\error.vue' /* webpackChunkName: "" */))
const _f3e6c2a4 = () => interopDefault(import('..\\pages\\about.vue' /* webpackChunkName: "pages/about" */))
const _6c746148 = () => interopDefault(import('..\\pages\\build-info.vue' /* webpackChunkName: "pages/build-info" */))
const _57197a96 = () => interopDefault(import('..\\pages\\career\\index.vue' /* webpackChunkName: "pages/career/index" */))
const _2a739c42 = () => interopDefault(import('..\\pages\\cart\\cart-new.vue' /* webpackChunkName: "" */))
const _e58e9ca6 = () => interopDefault(import('..\\pages\\checkout\\index.vue' /* webpackChunkName: "pages/checkout/index" */))
const _7141dc7c = () => interopDefault(import('..\\pages\\contacts.vue' /* webpackChunkName: "pages/contacts" */))
const _b4770d1a = () => interopDefault(import('..\\pages\\index.vue' /* webpackChunkName: "pages/index" */))
const _17801726 = () => interopDefault(import('..\\pages\\dev-checkout.vue' /* webpackChunkName: "pages/dev-checkout" */))
const _31acee18 = () => interopDefault(import('..\\pages\\docs\\index.vue' /* webpackChunkName: "pages/docs/index" */))
const _58c4ea3a = () => interopDefault(import('..\\pages\\events\\index.vue' /* webpackChunkName: "pages/events/index" */))
const _ccb47810 = () => interopDefault(import('..\\pages\\favorites.vue' /* webpackChunkName: "pages/favorites" */))
const _f85c9300 = () => interopDefault(import('..\\pages\\news\\index.vue' /* webpackChunkName: "pages/news/index" */))
const _7b03a946 = () => interopDefault(import('..\\pages\\polet.vue' /* webpackChunkName: "" */))
const _29f87c1b = () => interopDefault(import('..\\pages\\registration-confirm.vue' /* webpackChunkName: "pages/registration-confirm" */))
const _601f29e9 = () => interopDefault(import('..\\pages\\restore-password.vue' /* webpackChunkName: "pages/restore-password" */))
const _51ef2f7f = () => interopDefault(import('..\\pages\\storybook.vue' /* webpackChunkName: "pages/storybook" */))
const _007f8ee6 = () => interopDefault(import('..\\pages\\career\\example.vue' /* webpackChunkName: "pages/career/example" */))
const _5dec0de8 = () => interopDefault(import('..\\pages\\faq\\buyer.vue' /* webpackChunkName: "pages/faq/buyer" */))
const _96c26302 = () => interopDefault(import('..\\pages\\faq\\merchant.vue' /* webpackChunkName: "pages/faq/merchant" */))
const _12bf1650 = () => interopDefault(import('..\\pages\\account\\_page.vue' /* webpackChunkName: "" */))
const _3a78af00 = () => interopDefault(import('..\\pages\\catalog\\_slug.vue' /* webpackChunkName: "pages/catalog/_slug" */))
const _2ff64cd0 = () => interopDefault(import('..\\pages\\docs\\_slug.vue' /* webpackChunkName: "pages/docs/_slug" */))
const _570e48f2 = () => interopDefault(import('..\\pages\\events\\_slug.vue' /* webpackChunkName: "pages/events/_slug" */))
const _fbc9d590 = () => interopDefault(import('..\\pages\\news\\_slug.vue' /* webpackChunkName: "pages/news/_slug" */))
const _411aacfa = () => interopDefault(import('..\\pages\\order-status\\_slug.vue' /* webpackChunkName: "pages/order-status/_slug" */))
const _adef24f2 = () => interopDefault(import('..\\pages\\products\\_slug.vue' /* webpackChunkName: "pages/products/_slug" */))
const _b6ffebec = () => interopDefault(import('..\\pages\\promo\\_slug.vue' /* webpackChunkName: "pages/promo/_slug" */))
const _8b46b5fa = () => interopDefault(import('..\\pages\\search\\_slug.vue' /* webpackChunkName: "pages/search/_slug" */))
const _7bab7072 = () => interopDefault(import('..\\pages\\suppliers\\_slug.vue' /* webpackChunkName: "pages/suppliers/_slug" */))

// TODO: remove in Nuxt 3
const emptyFn = () => {}
const originalPush = Router.prototype.push
Router.prototype.push = function push (location, onComplete = emptyFn, onAbort) {
  return originalPush.call(this, location, onComplete, onAbort)
}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: decodeURI('/'),
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/en",
    redirect: "/"
  }, {
    path: "/404/",
    component: _99a7bef8,
    props: {"error":{"statusCode":404}},
    name: "error-404___en"
  }, {
    path: "/500/",
    component: _99a7bef8,
    props: {"error":{"statusCode":500}},
    name: "error-500___en"
  }, {
    path: "/about/",
    component: _f3e6c2a4,
    pathToRegexpOptions: {"strict":true},
    name: "about___en"
  }, {
    path: "/build-info/",
    component: _6c746148,
    pathToRegexpOptions: {"strict":true},
    name: "build-info___en"
  }, {
    path: "/career/",
    component: _57197a96,
    pathToRegexpOptions: {"strict":true},
    name: "career___en"
  }, {
    path: "/cart/",
    component: _2a739c42,
    name: "cart-new___en"
  }, {
    path: "/checkout/",
    component: _e58e9ca6,
    pathToRegexpOptions: {"strict":true},
    name: "checkout___en"
  }, {
    path: "/contacts/",
    component: _7141dc7c,
    pathToRegexpOptions: {"strict":true},
    name: "contacts___en"
  }, {
    path: "/de/",
    component: _b4770d1a,
    pathToRegexpOptions: {"strict":true},
    name: "index___de"
  }, {
    path: "/dev-checkout/",
    component: _17801726,
    pathToRegexpOptions: {"strict":true},
    name: "dev-checkout___en"
  }, {
    path: "/docs/",
    component: _31acee18,
    pathToRegexpOptions: {"strict":true},
    name: "docs___en"
  }, {
    path: "/en/",
    redirect: "/"
  }, {
    path: "/es/",
    component: _b4770d1a,
    pathToRegexpOptions: {"strict":true},
    name: "index___es"
  }, {
    path: "/events/",
    component: _58c4ea3a,
    pathToRegexpOptions: {"strict":true},
    name: "events___en"
  }, {
    path: "/favorites/",
    component: _ccb47810,
    pathToRegexpOptions: {"strict":true},
    name: "favorites___en"
  }, {
    path: "/fr/",
    component: _b4770d1a,
    pathToRegexpOptions: {"strict":true},
    name: "index___fr"
  }, {
    path: "/hi/",
    component: _b4770d1a,
    pathToRegexpOptions: {"strict":true},
    name: "index___hi"
  }, {
    path: "/it/",
    component: _b4770d1a,
    pathToRegexpOptions: {"strict":true},
    name: "index___it"
  }, {
    path: "/news/",
    component: _f85c9300,
    pathToRegexpOptions: {"strict":true},
    name: "news___en"
  }, {
    path: "/palekh-watch/",
    component: _7b03a946,
    name: "palekh-watch___en"
  }, {
    path: "/polet/",
    component: _7b03a946,
    pathToRegexpOptions: {"strict":true},
    name: "polet___en"
  }, {
    path: "/pt/",
    component: _b4770d1a,
    pathToRegexpOptions: {"strict":true},
    name: "index___pt"
  }, {
    path: "/registration-confirm/",
    component: _29f87c1b,
    pathToRegexpOptions: {"strict":true},
    name: "registration-confirm___en"
  }, {
    path: "/restore-password/",
    component: _601f29e9,
    pathToRegexpOptions: {"strict":true},
    name: "restore-password___en"
  }, {
    path: "/ru/",
    component: _b4770d1a,
    pathToRegexpOptions: {"strict":true},
    name: "index___ru"
  }, {
    path: "/storybook/",
    component: _51ef2f7f,
    pathToRegexpOptions: {"strict":true},
    name: "storybook___en"
  }, {
    path: "/tr/",
    component: _b4770d1a,
    pathToRegexpOptions: {"strict":true},
    name: "index___tr"
  }, {
    path: "/vi/",
    component: _b4770d1a,
    pathToRegexpOptions: {"strict":true},
    name: "index___vi"
  }, {
    path: "/zh/",
    component: _b4770d1a,
    pathToRegexpOptions: {"strict":true},
    name: "index___zh"
  }, {
    path: "/career/example/",
    component: _007f8ee6,
    pathToRegexpOptions: {"strict":true},
    name: "career-example___en"
  }, {
    path: "/cart/cart-new/",
    component: _2a739c42,
    pathToRegexpOptions: {"strict":true},
    name: "cart-cart-new___en"
  }, {
    path: "/de/404/",
    component: _99a7bef8,
    props: {"error":{"statusCode":404}},
    name: "error-404___de"
  }, {
    path: "/de/500/",
    component: _99a7bef8,
    props: {"error":{"statusCode":500}},
    name: "error-500___de"
  }, {
    path: "/de/about/",
    component: _f3e6c2a4,
    pathToRegexpOptions: {"strict":true},
    name: "about___de"
  }, {
    path: "/de/build-info/",
    component: _6c746148,
    pathToRegexpOptions: {"strict":true},
    name: "build-info___de"
  }, {
    path: "/de/career/",
    component: _57197a96,
    pathToRegexpOptions: {"strict":true},
    name: "career___de"
  }, {
    path: "/de/cart/",
    component: _2a739c42,
    name: "cart-new___de"
  }, {
    path: "/de/checkout/",
    component: _e58e9ca6,
    pathToRegexpOptions: {"strict":true},
    name: "checkout___de"
  }, {
    path: "/de/contacts/",
    component: _7141dc7c,
    pathToRegexpOptions: {"strict":true},
    name: "contacts___de"
  }, {
    path: "/de/dev-checkout/",
    component: _17801726,
    pathToRegexpOptions: {"strict":true},
    name: "dev-checkout___de"
  }, {
    path: "/de/docs/",
    component: _31acee18,
    pathToRegexpOptions: {"strict":true},
    name: "docs___de"
  }, {
    path: "/de/events/",
    component: _58c4ea3a,
    pathToRegexpOptions: {"strict":true},
    name: "events___de"
  }, {
    path: "/de/favorites/",
    component: _ccb47810,
    pathToRegexpOptions: {"strict":true},
    name: "favorites___de"
  }, {
    path: "/de/news/",
    component: _f85c9300,
    pathToRegexpOptions: {"strict":true},
    name: "news___de"
  }, {
    path: "/de/palekh-watch/",
    component: _7b03a946,
    name: "palekh-watch___de"
  }, {
    path: "/de/polet/",
    component: _7b03a946,
    pathToRegexpOptions: {"strict":true},
    name: "polet___de"
  }, {
    path: "/de/registration-confirm/",
    component: _29f87c1b,
    pathToRegexpOptions: {"strict":true},
    name: "registration-confirm___de"
  }, {
    path: "/de/restore-password/",
    component: _601f29e9,
    pathToRegexpOptions: {"strict":true},
    name: "restore-password___de"
  }, {
    path: "/de/storybook/",
    component: _51ef2f7f,
    pathToRegexpOptions: {"strict":true},
    name: "storybook___de"
  }, {
    path: "/es/404/",
    component: _99a7bef8,
    props: {"error":{"statusCode":404}},
    name: "error-404___es"
  }, {
    path: "/es/500/",
    component: _99a7bef8,
    props: {"error":{"statusCode":500}},
    name: "error-500___es"
  }, {
    path: "/es/about/",
    component: _f3e6c2a4,
    pathToRegexpOptions: {"strict":true},
    name: "about___es"
  }, {
    path: "/es/build-info/",
    component: _6c746148,
    pathToRegexpOptions: {"strict":true},
    name: "build-info___es"
  }, {
    path: "/es/career/",
    component: _57197a96,
    pathToRegexpOptions: {"strict":true},
    name: "career___es"
  }, {
    path: "/es/cart/",
    component: _2a739c42,
    name: "cart-new___es"
  }, {
    path: "/es/checkout/",
    component: _e58e9ca6,
    pathToRegexpOptions: {"strict":true},
    name: "checkout___es"
  }, {
    path: "/es/contacts/",
    component: _7141dc7c,
    pathToRegexpOptions: {"strict":true},
    name: "contacts___es"
  }, {
    path: "/es/dev-checkout/",
    component: _17801726,
    pathToRegexpOptions: {"strict":true},
    name: "dev-checkout___es"
  }, {
    path: "/es/docs/",
    component: _31acee18,
    pathToRegexpOptions: {"strict":true},
    name: "docs___es"
  }, {
    path: "/es/events/",
    component: _58c4ea3a,
    pathToRegexpOptions: {"strict":true},
    name: "events___es"
  }, {
    path: "/es/favorites/",
    component: _ccb47810,
    pathToRegexpOptions: {"strict":true},
    name: "favorites___es"
  }, {
    path: "/es/news/",
    component: _f85c9300,
    pathToRegexpOptions: {"strict":true},
    name: "news___es"
  }, {
    path: "/es/palekh-watch/",
    component: _7b03a946,
    name: "palekh-watch___es"
  }, {
    path: "/es/polet/",
    component: _7b03a946,
    pathToRegexpOptions: {"strict":true},
    name: "polet___es"
  }, {
    path: "/es/registration-confirm/",
    component: _29f87c1b,
    pathToRegexpOptions: {"strict":true},
    name: "registration-confirm___es"
  }, {
    path: "/es/restore-password/",
    component: _601f29e9,
    pathToRegexpOptions: {"strict":true},
    name: "restore-password___es"
  }, {
    path: "/es/storybook/",
    component: _51ef2f7f,
    pathToRegexpOptions: {"strict":true},
    name: "storybook___es"
  }, {
    path: "/faq/buyer/",
    component: _5dec0de8,
    pathToRegexpOptions: {"strict":true},
    name: "faq-buyer___en"
  }, {
    path: "/faq/merchant/",
    component: _96c26302,
    pathToRegexpOptions: {"strict":true},
    name: "faq-merchant___en"
  }, {
    path: "/fr/404/",
    component: _99a7bef8,
    props: {"error":{"statusCode":404}},
    name: "error-404___fr"
  }, {
    path: "/fr/500/",
    component: _99a7bef8,
    props: {"error":{"statusCode":500}},
    name: "error-500___fr"
  }, {
    path: "/fr/about/",
    component: _f3e6c2a4,
    pathToRegexpOptions: {"strict":true},
    name: "about___fr"
  }, {
    path: "/fr/build-info/",
    component: _6c746148,
    pathToRegexpOptions: {"strict":true},
    name: "build-info___fr"
  }, {
    path: "/fr/career/",
    component: _57197a96,
    pathToRegexpOptions: {"strict":true},
    name: "career___fr"
  }, {
    path: "/fr/cart/",
    component: _2a739c42,
    name: "cart-new___fr"
  }, {
    path: "/fr/checkout/",
    component: _e58e9ca6,
    pathToRegexpOptions: {"strict":true},
    name: "checkout___fr"
  }, {
    path: "/fr/contacts/",
    component: _7141dc7c,
    pathToRegexpOptions: {"strict":true},
    name: "contacts___fr"
  }, {
    path: "/fr/dev-checkout/",
    component: _17801726,
    pathToRegexpOptions: {"strict":true},
    name: "dev-checkout___fr"
  }, {
    path: "/fr/docs/",
    component: _31acee18,
    pathToRegexpOptions: {"strict":true},
    name: "docs___fr"
  }, {
    path: "/fr/events/",
    component: _58c4ea3a,
    pathToRegexpOptions: {"strict":true},
    name: "events___fr"
  }, {
    path: "/fr/favorites/",
    component: _ccb47810,
    pathToRegexpOptions: {"strict":true},
    name: "favorites___fr"
  }, {
    path: "/fr/news/",
    component: _f85c9300,
    pathToRegexpOptions: {"strict":true},
    name: "news___fr"
  }, {
    path: "/fr/palekh-watch/",
    component: _7b03a946,
    name: "palekh-watch___fr"
  }, {
    path: "/fr/polet/",
    component: _7b03a946,
    pathToRegexpOptions: {"strict":true},
    name: "polet___fr"
  }, {
    path: "/fr/registration-confirm/",
    component: _29f87c1b,
    pathToRegexpOptions: {"strict":true},
    name: "registration-confirm___fr"
  }, {
    path: "/fr/restore-password/",
    component: _601f29e9,
    pathToRegexpOptions: {"strict":true},
    name: "restore-password___fr"
  }, {
    path: "/fr/storybook/",
    component: _51ef2f7f,
    pathToRegexpOptions: {"strict":true},
    name: "storybook___fr"
  }, {
    path: "/hi/404/",
    component: _99a7bef8,
    props: {"error":{"statusCode":404}},
    name: "error-404___hi"
  }, {
    path: "/hi/500/",
    component: _99a7bef8,
    props: {"error":{"statusCode":500}},
    name: "error-500___hi"
  }, {
    path: "/hi/about/",
    component: _f3e6c2a4,
    pathToRegexpOptions: {"strict":true},
    name: "about___hi"
  }, {
    path: "/hi/build-info/",
    component: _6c746148,
    pathToRegexpOptions: {"strict":true},
    name: "build-info___hi"
  }, {
    path: "/hi/career/",
    component: _57197a96,
    pathToRegexpOptions: {"strict":true},
    name: "career___hi"
  }, {
    path: "/hi/cart/",
    component: _2a739c42,
    name: "cart-new___hi"
  }, {
    path: "/hi/checkout/",
    component: _e58e9ca6,
    pathToRegexpOptions: {"strict":true},
    name: "checkout___hi"
  }, {
    path: "/hi/contacts/",
    component: _7141dc7c,
    pathToRegexpOptions: {"strict":true},
    name: "contacts___hi"
  }, {
    path: "/hi/dev-checkout/",
    component: _17801726,
    pathToRegexpOptions: {"strict":true},
    name: "dev-checkout___hi"
  }, {
    path: "/hi/docs/",
    component: _31acee18,
    pathToRegexpOptions: {"strict":true},
    name: "docs___hi"
  }, {
    path: "/hi/events/",
    component: _58c4ea3a,
    pathToRegexpOptions: {"strict":true},
    name: "events___hi"
  }, {
    path: "/hi/favorites/",
    component: _ccb47810,
    pathToRegexpOptions: {"strict":true},
    name: "favorites___hi"
  }, {
    path: "/hi/news/",
    component: _f85c9300,
    pathToRegexpOptions: {"strict":true},
    name: "news___hi"
  }, {
    path: "/hi/palekh-watch/",
    component: _7b03a946,
    name: "palekh-watch___hi"
  }, {
    path: "/hi/polet/",
    component: _7b03a946,
    pathToRegexpOptions: {"strict":true},
    name: "polet___hi"
  }, {
    path: "/hi/registration-confirm/",
    component: _29f87c1b,
    pathToRegexpOptions: {"strict":true},
    name: "registration-confirm___hi"
  }, {
    path: "/hi/restore-password/",
    component: _601f29e9,
    pathToRegexpOptions: {"strict":true},
    name: "restore-password___hi"
  }, {
    path: "/hi/storybook/",
    component: _51ef2f7f,
    pathToRegexpOptions: {"strict":true},
    name: "storybook___hi"
  }, {
    path: "/info/about-us/",
    component: _f3e6c2a4,
    name: "about-us___en"
  }, {
    path: "/it/404/",
    component: _99a7bef8,
    props: {"error":{"statusCode":404}},
    name: "error-404___it"
  }, {
    path: "/it/500/",
    component: _99a7bef8,
    props: {"error":{"statusCode":500}},
    name: "error-500___it"
  }, {
    path: "/it/about/",
    component: _f3e6c2a4,
    pathToRegexpOptions: {"strict":true},
    name: "about___it"
  }, {
    path: "/it/build-info/",
    component: _6c746148,
    pathToRegexpOptions: {"strict":true},
    name: "build-info___it"
  }, {
    path: "/it/career/",
    component: _57197a96,
    pathToRegexpOptions: {"strict":true},
    name: "career___it"
  }, {
    path: "/it/cart/",
    component: _2a739c42,
    name: "cart-new___it"
  }, {
    path: "/it/checkout/",
    component: _e58e9ca6,
    pathToRegexpOptions: {"strict":true},
    name: "checkout___it"
  }, {
    path: "/it/contacts/",
    component: _7141dc7c,
    pathToRegexpOptions: {"strict":true},
    name: "contacts___it"
  }, {
    path: "/it/dev-checkout/",
    component: _17801726,
    pathToRegexpOptions: {"strict":true},
    name: "dev-checkout___it"
  }, {
    path: "/it/docs/",
    component: _31acee18,
    pathToRegexpOptions: {"strict":true},
    name: "docs___it"
  }, {
    path: "/it/events/",
    component: _58c4ea3a,
    pathToRegexpOptions: {"strict":true},
    name: "events___it"
  }, {
    path: "/it/favorites/",
    component: _ccb47810,
    pathToRegexpOptions: {"strict":true},
    name: "favorites___it"
  }, {
    path: "/it/news/",
    component: _f85c9300,
    pathToRegexpOptions: {"strict":true},
    name: "news___it"
  }, {
    path: "/it/palekh-watch/",
    component: _7b03a946,
    name: "palekh-watch___it"
  }, {
    path: "/it/polet/",
    component: _7b03a946,
    pathToRegexpOptions: {"strict":true},
    name: "polet___it"
  }, {
    path: "/it/registration-confirm/",
    component: _29f87c1b,
    pathToRegexpOptions: {"strict":true},
    name: "registration-confirm___it"
  }, {
    path: "/it/restore-password/",
    component: _601f29e9,
    pathToRegexpOptions: {"strict":true},
    name: "restore-password___it"
  }, {
    path: "/it/storybook/",
    component: _51ef2f7f,
    pathToRegexpOptions: {"strict":true},
    name: "storybook___it"
  }, {
    path: "/pt/404/",
    component: _99a7bef8,
    props: {"error":{"statusCode":404}},
    name: "error-404___pt"
  }, {
    path: "/pt/500/",
    component: _99a7bef8,
    props: {"error":{"statusCode":500}},
    name: "error-500___pt"
  }, {
    path: "/pt/about/",
    component: _f3e6c2a4,
    pathToRegexpOptions: {"strict":true},
    name: "about___pt"
  }, {
    path: "/pt/build-info/",
    component: _6c746148,
    pathToRegexpOptions: {"strict":true},
    name: "build-info___pt"
  }, {
    path: "/pt/career/",
    component: _57197a96,
    pathToRegexpOptions: {"strict":true},
    name: "career___pt"
  }, {
    path: "/pt/cart/",
    component: _2a739c42,
    name: "cart-new___pt"
  }, {
    path: "/pt/checkout/",
    component: _e58e9ca6,
    pathToRegexpOptions: {"strict":true},
    name: "checkout___pt"
  }, {
    path: "/pt/contacts/",
    component: _7141dc7c,
    pathToRegexpOptions: {"strict":true},
    name: "contacts___pt"
  }, {
    path: "/pt/dev-checkout/",
    component: _17801726,
    pathToRegexpOptions: {"strict":true},
    name: "dev-checkout___pt"
  }, {
    path: "/pt/docs/",
    component: _31acee18,
    pathToRegexpOptions: {"strict":true},
    name: "docs___pt"
  }, {
    path: "/pt/events/",
    component: _58c4ea3a,
    pathToRegexpOptions: {"strict":true},
    name: "events___pt"
  }, {
    path: "/pt/favorites/",
    component: _ccb47810,
    pathToRegexpOptions: {"strict":true},
    name: "favorites___pt"
  }, {
    path: "/pt/news/",
    component: _f85c9300,
    pathToRegexpOptions: {"strict":true},
    name: "news___pt"
  }, {
    path: "/pt/palekh-watch/",
    component: _7b03a946,
    name: "palekh-watch___pt"
  }, {
    path: "/pt/polet/",
    component: _7b03a946,
    pathToRegexpOptions: {"strict":true},
    name: "polet___pt"
  }, {
    path: "/pt/registration-confirm/",
    component: _29f87c1b,
    pathToRegexpOptions: {"strict":true},
    name: "registration-confirm___pt"
  }, {
    path: "/pt/restore-password/",
    component: _601f29e9,
    pathToRegexpOptions: {"strict":true},
    name: "restore-password___pt"
  }, {
    path: "/pt/storybook/",
    component: _51ef2f7f,
    pathToRegexpOptions: {"strict":true},
    name: "storybook___pt"
  }, {
    path: "/ru/404/",
    component: _99a7bef8,
    props: {"error":{"statusCode":404}},
    name: "error-404___ru"
  }, {
    path: "/ru/500/",
    component: _99a7bef8,
    props: {"error":{"statusCode":500}},
    name: "error-500___ru"
  }, {
    path: "/ru/about/",
    component: _f3e6c2a4,
    pathToRegexpOptions: {"strict":true},
    name: "about___ru"
  }, {
    path: "/ru/build-info/",
    component: _6c746148,
    pathToRegexpOptions: {"strict":true},
    name: "build-info___ru"
  }, {
    path: "/ru/career/",
    component: _57197a96,
    pathToRegexpOptions: {"strict":true},
    name: "career___ru"
  }, {
    path: "/ru/cart/",
    component: _2a739c42,
    name: "cart-new___ru"
  }, {
    path: "/ru/checkout/",
    component: _e58e9ca6,
    pathToRegexpOptions: {"strict":true},
    name: "checkout___ru"
  }, {
    path: "/ru/contacts/",
    component: _7141dc7c,
    pathToRegexpOptions: {"strict":true},
    name: "contacts___ru"
  }, {
    path: "/ru/dev-checkout/",
    component: _17801726,
    pathToRegexpOptions: {"strict":true},
    name: "dev-checkout___ru"
  }, {
    path: "/ru/docs/",
    component: _31acee18,
    pathToRegexpOptions: {"strict":true},
    name: "docs___ru"
  }, {
    path: "/ru/events/",
    component: _58c4ea3a,
    pathToRegexpOptions: {"strict":true},
    name: "events___ru"
  }, {
    path: "/ru/favorites/",
    component: _ccb47810,
    pathToRegexpOptions: {"strict":true},
    name: "favorites___ru"
  }, {
    path: "/ru/news/",
    component: _f85c9300,
    pathToRegexpOptions: {"strict":true},
    name: "news___ru"
  }, {
    path: "/ru/palekh-watch/",
    component: _7b03a946,
    name: "palekh-watch___ru"
  }, {
    path: "/ru/polet/",
    component: _7b03a946,
    pathToRegexpOptions: {"strict":true},
    name: "polet___ru"
  }, {
    path: "/ru/registration-confirm/",
    component: _29f87c1b,
    pathToRegexpOptions: {"strict":true},
    name: "registration-confirm___ru"
  }, {
    path: "/ru/restore-password/",
    component: _601f29e9,
    pathToRegexpOptions: {"strict":true},
    name: "restore-password___ru"
  }, {
    path: "/ru/storybook/",
    component: _51ef2f7f,
    pathToRegexpOptions: {"strict":true},
    name: "storybook___ru"
  }, {
    path: "/tr/404/",
    component: _99a7bef8,
    props: {"error":{"statusCode":404}},
    name: "error-404___tr"
  }, {
    path: "/tr/500/",
    component: _99a7bef8,
    props: {"error":{"statusCode":500}},
    name: "error-500___tr"
  }, {
    path: "/tr/about/",
    component: _f3e6c2a4,
    pathToRegexpOptions: {"strict":true},
    name: "about___tr"
  }, {
    path: "/tr/build-info/",
    component: _6c746148,
    pathToRegexpOptions: {"strict":true},
    name: "build-info___tr"
  }, {
    path: "/tr/career/",
    component: _57197a96,
    pathToRegexpOptions: {"strict":true},
    name: "career___tr"
  }, {
    path: "/tr/cart/",
    component: _2a739c42,
    name: "cart-new___tr"
  }, {
    path: "/tr/checkout/",
    component: _e58e9ca6,
    pathToRegexpOptions: {"strict":true},
    name: "checkout___tr"
  }, {
    path: "/tr/contacts/",
    component: _7141dc7c,
    pathToRegexpOptions: {"strict":true},
    name: "contacts___tr"
  }, {
    path: "/tr/dev-checkout/",
    component: _17801726,
    pathToRegexpOptions: {"strict":true},
    name: "dev-checkout___tr"
  }, {
    path: "/tr/docs/",
    component: _31acee18,
    pathToRegexpOptions: {"strict":true},
    name: "docs___tr"
  }, {
    path: "/tr/events/",
    component: _58c4ea3a,
    pathToRegexpOptions: {"strict":true},
    name: "events___tr"
  }, {
    path: "/tr/favorites/",
    component: _ccb47810,
    pathToRegexpOptions: {"strict":true},
    name: "favorites___tr"
  }, {
    path: "/tr/news/",
    component: _f85c9300,
    pathToRegexpOptions: {"strict":true},
    name: "news___tr"
  }, {
    path: "/tr/palekh-watch/",
    component: _7b03a946,
    name: "palekh-watch___tr"
  }, {
    path: "/tr/polet/",
    component: _7b03a946,
    pathToRegexpOptions: {"strict":true},
    name: "polet___tr"
  }, {
    path: "/tr/registration-confirm/",
    component: _29f87c1b,
    pathToRegexpOptions: {"strict":true},
    name: "registration-confirm___tr"
  }, {
    path: "/tr/restore-password/",
    component: _601f29e9,
    pathToRegexpOptions: {"strict":true},
    name: "restore-password___tr"
  }, {
    path: "/tr/storybook/",
    component: _51ef2f7f,
    pathToRegexpOptions: {"strict":true},
    name: "storybook___tr"
  }, {
    path: "/vi/404/",
    component: _99a7bef8,
    props: {"error":{"statusCode":404}},
    name: "error-404___vi"
  }, {
    path: "/vi/500/",
    component: _99a7bef8,
    props: {"error":{"statusCode":500}},
    name: "error-500___vi"
  }, {
    path: "/vi/about/",
    component: _f3e6c2a4,
    pathToRegexpOptions: {"strict":true},
    name: "about___vi"
  }, {
    path: "/vi/build-info/",
    component: _6c746148,
    pathToRegexpOptions: {"strict":true},
    name: "build-info___vi"
  }, {
    path: "/vi/career/",
    component: _57197a96,
    pathToRegexpOptions: {"strict":true},
    name: "career___vi"
  }, {
    path: "/vi/cart/",
    component: _2a739c42,
    name: "cart-new___vi"
  }, {
    path: "/vi/checkout/",
    component: _e58e9ca6,
    pathToRegexpOptions: {"strict":true},
    name: "checkout___vi"
  }, {
    path: "/vi/contacts/",
    component: _7141dc7c,
    pathToRegexpOptions: {"strict":true},
    name: "contacts___vi"
  }, {
    path: "/vi/dev-checkout/",
    component: _17801726,
    pathToRegexpOptions: {"strict":true},
    name: "dev-checkout___vi"
  }, {
    path: "/vi/docs/",
    component: _31acee18,
    pathToRegexpOptions: {"strict":true},
    name: "docs___vi"
  }, {
    path: "/vi/events/",
    component: _58c4ea3a,
    pathToRegexpOptions: {"strict":true},
    name: "events___vi"
  }, {
    path: "/vi/favorites/",
    component: _ccb47810,
    pathToRegexpOptions: {"strict":true},
    name: "favorites___vi"
  }, {
    path: "/vi/news/",
    component: _f85c9300,
    pathToRegexpOptions: {"strict":true},
    name: "news___vi"
  }, {
    path: "/vi/palekh-watch/",
    component: _7b03a946,
    name: "palekh-watch___vi"
  }, {
    path: "/vi/polet/",
    component: _7b03a946,
    pathToRegexpOptions: {"strict":true},
    name: "polet___vi"
  }, {
    path: "/vi/registration-confirm/",
    component: _29f87c1b,
    pathToRegexpOptions: {"strict":true},
    name: "registration-confirm___vi"
  }, {
    path: "/vi/restore-password/",
    component: _601f29e9,
    pathToRegexpOptions: {"strict":true},
    name: "restore-password___vi"
  }, {
    path: "/vi/storybook/",
    component: _51ef2f7f,
    pathToRegexpOptions: {"strict":true},
    name: "storybook___vi"
  }, {
    path: "/zh/404/",
    component: _99a7bef8,
    props: {"error":{"statusCode":404}},
    name: "error-404___zh"
  }, {
    path: "/zh/500/",
    component: _99a7bef8,
    props: {"error":{"statusCode":500}},
    name: "error-500___zh"
  }, {
    path: "/zh/about/",
    component: _f3e6c2a4,
    pathToRegexpOptions: {"strict":true},
    name: "about___zh"
  }, {
    path: "/zh/build-info/",
    component: _6c746148,
    pathToRegexpOptions: {"strict":true},
    name: "build-info___zh"
  }, {
    path: "/zh/career/",
    component: _57197a96,
    pathToRegexpOptions: {"strict":true},
    name: "career___zh"
  }, {
    path: "/zh/cart/",
    component: _2a739c42,
    name: "cart-new___zh"
  }, {
    path: "/zh/checkout/",
    component: _e58e9ca6,
    pathToRegexpOptions: {"strict":true},
    name: "checkout___zh"
  }, {
    path: "/zh/contacts/",
    component: _7141dc7c,
    pathToRegexpOptions: {"strict":true},
    name: "contacts___zh"
  }, {
    path: "/zh/dev-checkout/",
    component: _17801726,
    pathToRegexpOptions: {"strict":true},
    name: "dev-checkout___zh"
  }, {
    path: "/zh/docs/",
    component: _31acee18,
    pathToRegexpOptions: {"strict":true},
    name: "docs___zh"
  }, {
    path: "/zh/events/",
    component: _58c4ea3a,
    pathToRegexpOptions: {"strict":true},
    name: "events___zh"
  }, {
    path: "/zh/favorites/",
    component: _ccb47810,
    pathToRegexpOptions: {"strict":true},
    name: "favorites___zh"
  }, {
    path: "/zh/news/",
    component: _f85c9300,
    pathToRegexpOptions: {"strict":true},
    name: "news___zh"
  }, {
    path: "/zh/palekh-watch/",
    component: _7b03a946,
    name: "palekh-watch___zh"
  }, {
    path: "/zh/polet/",
    component: _7b03a946,
    pathToRegexpOptions: {"strict":true},
    name: "polet___zh"
  }, {
    path: "/zh/registration-confirm/",
    component: _29f87c1b,
    pathToRegexpOptions: {"strict":true},
    name: "registration-confirm___zh"
  }, {
    path: "/zh/restore-password/",
    component: _601f29e9,
    pathToRegexpOptions: {"strict":true},
    name: "restore-password___zh"
  }, {
    path: "/zh/storybook/",
    component: _51ef2f7f,
    pathToRegexpOptions: {"strict":true},
    name: "storybook___zh"
  }, {
    path: "/de/career/example/",
    component: _007f8ee6,
    pathToRegexpOptions: {"strict":true},
    name: "career-example___de"
  }, {
    path: "/de/cart/cart-new/",
    component: _2a739c42,
    pathToRegexpOptions: {"strict":true},
    name: "cart-cart-new___de"
  }, {
    path: "/de/faq/buyer/",
    component: _5dec0de8,
    pathToRegexpOptions: {"strict":true},
    name: "faq-buyer___de"
  }, {
    path: "/de/faq/merchant/",
    component: _96c26302,
    pathToRegexpOptions: {"strict":true},
    name: "faq-merchant___de"
  }, {
    path: "/de/info/about-us/",
    component: _f3e6c2a4,
    name: "about-us___de"
  }, {
    path: "/es/career/example/",
    component: _007f8ee6,
    pathToRegexpOptions: {"strict":true},
    name: "career-example___es"
  }, {
    path: "/es/cart/cart-new/",
    component: _2a739c42,
    pathToRegexpOptions: {"strict":true},
    name: "cart-cart-new___es"
  }, {
    path: "/es/faq/buyer/",
    component: _5dec0de8,
    pathToRegexpOptions: {"strict":true},
    name: "faq-buyer___es"
  }, {
    path: "/es/faq/merchant/",
    component: _96c26302,
    pathToRegexpOptions: {"strict":true},
    name: "faq-merchant___es"
  }, {
    path: "/es/info/about-us/",
    component: _f3e6c2a4,
    name: "about-us___es"
  }, {
    path: "/fr/career/example/",
    component: _007f8ee6,
    pathToRegexpOptions: {"strict":true},
    name: "career-example___fr"
  }, {
    path: "/fr/cart/cart-new/",
    component: _2a739c42,
    pathToRegexpOptions: {"strict":true},
    name: "cart-cart-new___fr"
  }, {
    path: "/fr/faq/buyer/",
    component: _5dec0de8,
    pathToRegexpOptions: {"strict":true},
    name: "faq-buyer___fr"
  }, {
    path: "/fr/faq/merchant/",
    component: _96c26302,
    pathToRegexpOptions: {"strict":true},
    name: "faq-merchant___fr"
  }, {
    path: "/fr/info/about-us/",
    component: _f3e6c2a4,
    name: "about-us___fr"
  }, {
    path: "/hi/career/example/",
    component: _007f8ee6,
    pathToRegexpOptions: {"strict":true},
    name: "career-example___hi"
  }, {
    path: "/hi/cart/cart-new/",
    component: _2a739c42,
    pathToRegexpOptions: {"strict":true},
    name: "cart-cart-new___hi"
  }, {
    path: "/hi/faq/buyer/",
    component: _5dec0de8,
    pathToRegexpOptions: {"strict":true},
    name: "faq-buyer___hi"
  }, {
    path: "/hi/faq/merchant/",
    component: _96c26302,
    pathToRegexpOptions: {"strict":true},
    name: "faq-merchant___hi"
  }, {
    path: "/hi/info/about-us/",
    component: _f3e6c2a4,
    name: "about-us___hi"
  }, {
    path: "/it/career/example/",
    component: _007f8ee6,
    pathToRegexpOptions: {"strict":true},
    name: "career-example___it"
  }, {
    path: "/it/cart/cart-new/",
    component: _2a739c42,
    pathToRegexpOptions: {"strict":true},
    name: "cart-cart-new___it"
  }, {
    path: "/it/faq/buyer/",
    component: _5dec0de8,
    pathToRegexpOptions: {"strict":true},
    name: "faq-buyer___it"
  }, {
    path: "/it/faq/merchant/",
    component: _96c26302,
    pathToRegexpOptions: {"strict":true},
    name: "faq-merchant___it"
  }, {
    path: "/it/info/about-us/",
    component: _f3e6c2a4,
    name: "about-us___it"
  }, {
    path: "/pt/career/example/",
    component: _007f8ee6,
    pathToRegexpOptions: {"strict":true},
    name: "career-example___pt"
  }, {
    path: "/pt/cart/cart-new/",
    component: _2a739c42,
    pathToRegexpOptions: {"strict":true},
    name: "cart-cart-new___pt"
  }, {
    path: "/pt/faq/buyer/",
    component: _5dec0de8,
    pathToRegexpOptions: {"strict":true},
    name: "faq-buyer___pt"
  }, {
    path: "/pt/faq/merchant/",
    component: _96c26302,
    pathToRegexpOptions: {"strict":true},
    name: "faq-merchant___pt"
  }, {
    path: "/pt/info/about-us/",
    component: _f3e6c2a4,
    name: "about-us___pt"
  }, {
    path: "/ru/career/example/",
    component: _007f8ee6,
    pathToRegexpOptions: {"strict":true},
    name: "career-example___ru"
  }, {
    path: "/ru/cart/cart-new/",
    component: _2a739c42,
    pathToRegexpOptions: {"strict":true},
    name: "cart-cart-new___ru"
  }, {
    path: "/ru/faq/buyer/",
    component: _5dec0de8,
    pathToRegexpOptions: {"strict":true},
    name: "faq-buyer___ru"
  }, {
    path: "/ru/faq/merchant/",
    component: _96c26302,
    pathToRegexpOptions: {"strict":true},
    name: "faq-merchant___ru"
  }, {
    path: "/ru/info/about-us/",
    component: _f3e6c2a4,
    name: "about-us___ru"
  }, {
    path: "/tr/career/example/",
    component: _007f8ee6,
    pathToRegexpOptions: {"strict":true},
    name: "career-example___tr"
  }, {
    path: "/tr/cart/cart-new/",
    component: _2a739c42,
    pathToRegexpOptions: {"strict":true},
    name: "cart-cart-new___tr"
  }, {
    path: "/tr/faq/buyer/",
    component: _5dec0de8,
    pathToRegexpOptions: {"strict":true},
    name: "faq-buyer___tr"
  }, {
    path: "/tr/faq/merchant/",
    component: _96c26302,
    pathToRegexpOptions: {"strict":true},
    name: "faq-merchant___tr"
  }, {
    path: "/tr/info/about-us/",
    component: _f3e6c2a4,
    name: "about-us___tr"
  }, {
    path: "/vi/career/example/",
    component: _007f8ee6,
    pathToRegexpOptions: {"strict":true},
    name: "career-example___vi"
  }, {
    path: "/vi/cart/cart-new/",
    component: _2a739c42,
    pathToRegexpOptions: {"strict":true},
    name: "cart-cart-new___vi"
  }, {
    path: "/vi/faq/buyer/",
    component: _5dec0de8,
    pathToRegexpOptions: {"strict":true},
    name: "faq-buyer___vi"
  }, {
    path: "/vi/faq/merchant/",
    component: _96c26302,
    pathToRegexpOptions: {"strict":true},
    name: "faq-merchant___vi"
  }, {
    path: "/vi/info/about-us/",
    component: _f3e6c2a4,
    name: "about-us___vi"
  }, {
    path: "/zh/career/example/",
    component: _007f8ee6,
    pathToRegexpOptions: {"strict":true},
    name: "career-example___zh"
  }, {
    path: "/zh/cart/cart-new/",
    component: _2a739c42,
    pathToRegexpOptions: {"strict":true},
    name: "cart-cart-new___zh"
  }, {
    path: "/zh/faq/buyer/",
    component: _5dec0de8,
    pathToRegexpOptions: {"strict":true},
    name: "faq-buyer___zh"
  }, {
    path: "/zh/faq/merchant/",
    component: _96c26302,
    pathToRegexpOptions: {"strict":true},
    name: "faq-merchant___zh"
  }, {
    path: "/zh/info/about-us/",
    component: _f3e6c2a4,
    name: "about-us___zh"
  }, {
    path: "/de/account/orders/:id/",
    component: _12bf1650,
    name: "account-order-id___de"
  }, {
    path: "/de/events/year/:year/",
    component: _58c4ea3a,
    name: "event-in-year___de"
  }, {
    path: "/es/account/orders/:id/",
    component: _12bf1650,
    name: "account-order-id___es"
  }, {
    path: "/es/events/year/:year/",
    component: _58c4ea3a,
    name: "event-in-year___es"
  }, {
    path: "/fr/account/orders/:id/",
    component: _12bf1650,
    name: "account-order-id___fr"
  }, {
    path: "/fr/events/year/:year/",
    component: _58c4ea3a,
    name: "event-in-year___fr"
  }, {
    path: "/hi/account/orders/:id/",
    component: _12bf1650,
    name: "account-order-id___hi"
  }, {
    path: "/hi/events/year/:year/",
    component: _58c4ea3a,
    name: "event-in-year___hi"
  }, {
    path: "/it/account/orders/:id/",
    component: _12bf1650,
    name: "account-order-id___it"
  }, {
    path: "/it/events/year/:year/",
    component: _58c4ea3a,
    name: "event-in-year___it"
  }, {
    path: "/pt/account/orders/:id/",
    component: _12bf1650,
    name: "account-order-id___pt"
  }, {
    path: "/pt/events/year/:year/",
    component: _58c4ea3a,
    name: "event-in-year___pt"
  }, {
    path: "/ru/account/orders/:id/",
    component: _12bf1650,
    name: "account-order-id___ru"
  }, {
    path: "/ru/events/year/:year/",
    component: _58c4ea3a,
    name: "event-in-year___ru"
  }, {
    path: "/tr/account/orders/:id/",
    component: _12bf1650,
    name: "account-order-id___tr"
  }, {
    path: "/tr/events/year/:year/",
    component: _58c4ea3a,
    name: "event-in-year___tr"
  }, {
    path: "/vi/account/orders/:id/",
    component: _12bf1650,
    name: "account-order-id___vi"
  }, {
    path: "/vi/events/year/:year/",
    component: _58c4ea3a,
    name: "event-in-year___vi"
  }, {
    path: "/zh/account/orders/:id/",
    component: _12bf1650,
    name: "account-order-id___zh"
  }, {
    path: "/zh/events/year/:year/",
    component: _58c4ea3a,
    name: "event-in-year___zh"
  }, {
    path: "/de/events/year/:year/month/:month/",
    component: _58c4ea3a,
    name: "event-in-month___de"
  }, {
    path: "/es/events/year/:year/month/:month/",
    component: _58c4ea3a,
    name: "event-in-month___es"
  }, {
    path: "/fr/events/year/:year/month/:month/",
    component: _58c4ea3a,
    name: "event-in-month___fr"
  }, {
    path: "/hi/events/year/:year/month/:month/",
    component: _58c4ea3a,
    name: "event-in-month___hi"
  }, {
    path: "/it/events/year/:year/month/:month/",
    component: _58c4ea3a,
    name: "event-in-month___it"
  }, {
    path: "/pt/events/year/:year/month/:month/",
    component: _58c4ea3a,
    name: "event-in-month___pt"
  }, {
    path: "/ru/events/year/:year/month/:month/",
    component: _58c4ea3a,
    name: "event-in-month___ru"
  }, {
    path: "/tr/events/year/:year/month/:month/",
    component: _58c4ea3a,
    name: "event-in-month___tr"
  }, {
    path: "/vi/events/year/:year/month/:month/",
    component: _58c4ea3a,
    name: "event-in-month___vi"
  }, {
    path: "/zh/events/year/:year/month/:month/",
    component: _58c4ea3a,
    name: "event-in-month___zh"
  }, {
    path: "/account/orders/:id/",
    component: _12bf1650,
    name: "account-order-id___en"
  }, {
    path: "/de/account/:page?/",
    component: _12bf1650,
    pathToRegexpOptions: {"strict":true},
    name: "account-page___de"
  }, {
    path: "/de/account/:page/",
    component: _12bf1650,
    name: "account___de"
  }, {
    path: "/de/account/:page/",
    component: _12bf1650,
    name: "account-orders___de"
  }, {
    path: "/de/catalog/:slug?/",
    component: _3a78af00,
    pathToRegexpOptions: {"strict":true},
    name: "catalog-slug___de"
  }, {
    path: "/de/docs/:slug/",
    component: _2ff64cd0,
    pathToRegexpOptions: {"strict":true},
    name: "docs-slug___de"
  }, {
    path: "/de/events/:slug/",
    component: _570e48f2,
    pathToRegexpOptions: {"strict":true},
    name: "events-slug___de"
  }, {
    path: "/de/news/:slug/",
    component: _fbc9d590,
    pathToRegexpOptions: {"strict":true},
    name: "news-slug___de"
  }, {
    path: "/de/order-status/:slug?/",
    component: _411aacfa,
    pathToRegexpOptions: {"strict":true},
    name: "order-status-slug___de"
  }, {
    path: "/de/products/:slug?/",
    component: _adef24f2,
    pathToRegexpOptions: {"strict":true},
    name: "products-slug___de"
  }, {
    path: "/de/promo/:slug?/",
    component: _b6ffebec,
    pathToRegexpOptions: {"strict":true},
    name: "promo-slug___de"
  }, {
    path: "/de/search/:slug?/",
    component: _8b46b5fa,
    pathToRegexpOptions: {"strict":true},
    name: "search-slug___de"
  }, {
    path: "/de/suppliers/:slug?/",
    component: _7bab7072,
    pathToRegexpOptions: {"strict":true},
    name: "suppliers-slug___de"
  }, {
    path: "/es/account/:page?/",
    component: _12bf1650,
    pathToRegexpOptions: {"strict":true},
    name: "account-page___es"
  }, {
    path: "/es/account/:page/",
    component: _12bf1650,
    name: "account___es"
  }, {
    path: "/es/account/:page/",
    component: _12bf1650,
    name: "account-orders___es"
  }, {
    path: "/es/catalog/:slug?/",
    component: _3a78af00,
    pathToRegexpOptions: {"strict":true},
    name: "catalog-slug___es"
  }, {
    path: "/es/docs/:slug/",
    component: _2ff64cd0,
    pathToRegexpOptions: {"strict":true},
    name: "docs-slug___es"
  }, {
    path: "/es/events/:slug/",
    component: _570e48f2,
    pathToRegexpOptions: {"strict":true},
    name: "events-slug___es"
  }, {
    path: "/es/news/:slug/",
    component: _fbc9d590,
    pathToRegexpOptions: {"strict":true},
    name: "news-slug___es"
  }, {
    path: "/es/order-status/:slug?/",
    component: _411aacfa,
    pathToRegexpOptions: {"strict":true},
    name: "order-status-slug___es"
  }, {
    path: "/es/products/:slug?/",
    component: _adef24f2,
    pathToRegexpOptions: {"strict":true},
    name: "products-slug___es"
  }, {
    path: "/es/promo/:slug?/",
    component: _b6ffebec,
    pathToRegexpOptions: {"strict":true},
    name: "promo-slug___es"
  }, {
    path: "/es/search/:slug?/",
    component: _8b46b5fa,
    pathToRegexpOptions: {"strict":true},
    name: "search-slug___es"
  }, {
    path: "/es/suppliers/:slug?/",
    component: _7bab7072,
    pathToRegexpOptions: {"strict":true},
    name: "suppliers-slug___es"
  }, {
    path: "/events/year/:year/",
    component: _58c4ea3a,
    name: "event-in-year___en"
  }, {
    path: "/fr/account/:page?/",
    component: _12bf1650,
    pathToRegexpOptions: {"strict":true},
    name: "account-page___fr"
  }, {
    path: "/fr/account/:page/",
    component: _12bf1650,
    name: "account___fr"
  }, {
    path: "/fr/account/:page/",
    component: _12bf1650,
    name: "account-orders___fr"
  }, {
    path: "/fr/catalog/:slug?/",
    component: _3a78af00,
    pathToRegexpOptions: {"strict":true},
    name: "catalog-slug___fr"
  }, {
    path: "/fr/docs/:slug/",
    component: _2ff64cd0,
    pathToRegexpOptions: {"strict":true},
    name: "docs-slug___fr"
  }, {
    path: "/fr/events/:slug/",
    component: _570e48f2,
    pathToRegexpOptions: {"strict":true},
    name: "events-slug___fr"
  }, {
    path: "/fr/news/:slug/",
    component: _fbc9d590,
    pathToRegexpOptions: {"strict":true},
    name: "news-slug___fr"
  }, {
    path: "/fr/order-status/:slug?/",
    component: _411aacfa,
    pathToRegexpOptions: {"strict":true},
    name: "order-status-slug___fr"
  }, {
    path: "/fr/products/:slug?/",
    component: _adef24f2,
    pathToRegexpOptions: {"strict":true},
    name: "products-slug___fr"
  }, {
    path: "/fr/promo/:slug?/",
    component: _b6ffebec,
    pathToRegexpOptions: {"strict":true},
    name: "promo-slug___fr"
  }, {
    path: "/fr/search/:slug?/",
    component: _8b46b5fa,
    pathToRegexpOptions: {"strict":true},
    name: "search-slug___fr"
  }, {
    path: "/fr/suppliers/:slug?/",
    component: _7bab7072,
    pathToRegexpOptions: {"strict":true},
    name: "suppliers-slug___fr"
  }, {
    path: "/hi/account/:page?/",
    component: _12bf1650,
    pathToRegexpOptions: {"strict":true},
    name: "account-page___hi"
  }, {
    path: "/hi/account/:page/",
    component: _12bf1650,
    name: "account___hi"
  }, {
    path: "/hi/account/:page/",
    component: _12bf1650,
    name: "account-orders___hi"
  }, {
    path: "/hi/catalog/:slug?/",
    component: _3a78af00,
    pathToRegexpOptions: {"strict":true},
    name: "catalog-slug___hi"
  }, {
    path: "/hi/docs/:slug/",
    component: _2ff64cd0,
    pathToRegexpOptions: {"strict":true},
    name: "docs-slug___hi"
  }, {
    path: "/hi/events/:slug/",
    component: _570e48f2,
    pathToRegexpOptions: {"strict":true},
    name: "events-slug___hi"
  }, {
    path: "/hi/news/:slug/",
    component: _fbc9d590,
    pathToRegexpOptions: {"strict":true},
    name: "news-slug___hi"
  }, {
    path: "/hi/order-status/:slug?/",
    component: _411aacfa,
    pathToRegexpOptions: {"strict":true},
    name: "order-status-slug___hi"
  }, {
    path: "/hi/products/:slug?/",
    component: _adef24f2,
    pathToRegexpOptions: {"strict":true},
    name: "products-slug___hi"
  }, {
    path: "/hi/promo/:slug?/",
    component: _b6ffebec,
    pathToRegexpOptions: {"strict":true},
    name: "promo-slug___hi"
  }, {
    path: "/hi/search/:slug?/",
    component: _8b46b5fa,
    pathToRegexpOptions: {"strict":true},
    name: "search-slug___hi"
  }, {
    path: "/hi/suppliers/:slug?/",
    component: _7bab7072,
    pathToRegexpOptions: {"strict":true},
    name: "suppliers-slug___hi"
  }, {
    path: "/it/account/:page?/",
    component: _12bf1650,
    pathToRegexpOptions: {"strict":true},
    name: "account-page___it"
  }, {
    path: "/it/account/:page/",
    component: _12bf1650,
    name: "account___it"
  }, {
    path: "/it/account/:page/",
    component: _12bf1650,
    name: "account-orders___it"
  }, {
    path: "/it/catalog/:slug?/",
    component: _3a78af00,
    pathToRegexpOptions: {"strict":true},
    name: "catalog-slug___it"
  }, {
    path: "/it/docs/:slug/",
    component: _2ff64cd0,
    pathToRegexpOptions: {"strict":true},
    name: "docs-slug___it"
  }, {
    path: "/it/events/:slug/",
    component: _570e48f2,
    pathToRegexpOptions: {"strict":true},
    name: "events-slug___it"
  }, {
    path: "/it/news/:slug/",
    component: _fbc9d590,
    pathToRegexpOptions: {"strict":true},
    name: "news-slug___it"
  }, {
    path: "/it/order-status/:slug?/",
    component: _411aacfa,
    pathToRegexpOptions: {"strict":true},
    name: "order-status-slug___it"
  }, {
    path: "/it/products/:slug?/",
    component: _adef24f2,
    pathToRegexpOptions: {"strict":true},
    name: "products-slug___it"
  }, {
    path: "/it/promo/:slug?/",
    component: _b6ffebec,
    pathToRegexpOptions: {"strict":true},
    name: "promo-slug___it"
  }, {
    path: "/it/search/:slug?/",
    component: _8b46b5fa,
    pathToRegexpOptions: {"strict":true},
    name: "search-slug___it"
  }, {
    path: "/it/suppliers/:slug?/",
    component: _7bab7072,
    pathToRegexpOptions: {"strict":true},
    name: "suppliers-slug___it"
  }, {
    path: "/pt/account/:page?/",
    component: _12bf1650,
    pathToRegexpOptions: {"strict":true},
    name: "account-page___pt"
  }, {
    path: "/pt/account/:page/",
    component: _12bf1650,
    name: "account___pt"
  }, {
    path: "/pt/account/:page/",
    component: _12bf1650,
    name: "account-orders___pt"
  }, {
    path: "/pt/catalog/:slug?/",
    component: _3a78af00,
    pathToRegexpOptions: {"strict":true},
    name: "catalog-slug___pt"
  }, {
    path: "/pt/docs/:slug/",
    component: _2ff64cd0,
    pathToRegexpOptions: {"strict":true},
    name: "docs-slug___pt"
  }, {
    path: "/pt/events/:slug/",
    component: _570e48f2,
    pathToRegexpOptions: {"strict":true},
    name: "events-slug___pt"
  }, {
    path: "/pt/news/:slug/",
    component: _fbc9d590,
    pathToRegexpOptions: {"strict":true},
    name: "news-slug___pt"
  }, {
    path: "/pt/order-status/:slug?/",
    component: _411aacfa,
    pathToRegexpOptions: {"strict":true},
    name: "order-status-slug___pt"
  }, {
    path: "/pt/products/:slug?/",
    component: _adef24f2,
    pathToRegexpOptions: {"strict":true},
    name: "products-slug___pt"
  }, {
    path: "/pt/promo/:slug?/",
    component: _b6ffebec,
    pathToRegexpOptions: {"strict":true},
    name: "promo-slug___pt"
  }, {
    path: "/pt/search/:slug?/",
    component: _8b46b5fa,
    pathToRegexpOptions: {"strict":true},
    name: "search-slug___pt"
  }, {
    path: "/pt/suppliers/:slug?/",
    component: _7bab7072,
    pathToRegexpOptions: {"strict":true},
    name: "suppliers-slug___pt"
  }, {
    path: "/ru/account/:page?/",
    component: _12bf1650,
    pathToRegexpOptions: {"strict":true},
    name: "account-page___ru"
  }, {
    path: "/ru/account/:page/",
    component: _12bf1650,
    name: "account___ru"
  }, {
    path: "/ru/account/:page/",
    component: _12bf1650,
    name: "account-orders___ru"
  }, {
    path: "/ru/catalog/:slug?/",
    component: _3a78af00,
    pathToRegexpOptions: {"strict":true},
    name: "catalog-slug___ru"
  }, {
    path: "/ru/docs/:slug/",
    component: _2ff64cd0,
    pathToRegexpOptions: {"strict":true},
    name: "docs-slug___ru"
  }, {
    path: "/ru/events/:slug/",
    component: _570e48f2,
    pathToRegexpOptions: {"strict":true},
    name: "events-slug___ru"
  }, {
    path: "/ru/news/:slug/",
    component: _fbc9d590,
    pathToRegexpOptions: {"strict":true},
    name: "news-slug___ru"
  }, {
    path: "/ru/order-status/:slug?/",
    component: _411aacfa,
    pathToRegexpOptions: {"strict":true},
    name: "order-status-slug___ru"
  }, {
    path: "/ru/products/:slug?/",
    component: _adef24f2,
    pathToRegexpOptions: {"strict":true},
    name: "products-slug___ru"
  }, {
    path: "/ru/promo/:slug?/",
    component: _b6ffebec,
    pathToRegexpOptions: {"strict":true},
    name: "promo-slug___ru"
  }, {
    path: "/ru/search/:slug?/",
    component: _8b46b5fa,
    pathToRegexpOptions: {"strict":true},
    name: "search-slug___ru"
  }, {
    path: "/ru/suppliers/:slug?/",
    component: _7bab7072,
    pathToRegexpOptions: {"strict":true},
    name: "suppliers-slug___ru"
  }, {
    path: "/tr/account/:page?/",
    component: _12bf1650,
    pathToRegexpOptions: {"strict":true},
    name: "account-page___tr"
  }, {
    path: "/tr/account/:page/",
    component: _12bf1650,
    name: "account___tr"
  }, {
    path: "/tr/account/:page/",
    component: _12bf1650,
    name: "account-orders___tr"
  }, {
    path: "/tr/catalog/:slug?/",
    component: _3a78af00,
    pathToRegexpOptions: {"strict":true},
    name: "catalog-slug___tr"
  }, {
    path: "/tr/docs/:slug/",
    component: _2ff64cd0,
    pathToRegexpOptions: {"strict":true},
    name: "docs-slug___tr"
  }, {
    path: "/tr/events/:slug/",
    component: _570e48f2,
    pathToRegexpOptions: {"strict":true},
    name: "events-slug___tr"
  }, {
    path: "/tr/news/:slug/",
    component: _fbc9d590,
    pathToRegexpOptions: {"strict":true},
    name: "news-slug___tr"
  }, {
    path: "/tr/order-status/:slug?/",
    component: _411aacfa,
    pathToRegexpOptions: {"strict":true},
    name: "order-status-slug___tr"
  }, {
    path: "/tr/products/:slug?/",
    component: _adef24f2,
    pathToRegexpOptions: {"strict":true},
    name: "products-slug___tr"
  }, {
    path: "/tr/promo/:slug?/",
    component: _b6ffebec,
    pathToRegexpOptions: {"strict":true},
    name: "promo-slug___tr"
  }, {
    path: "/tr/search/:slug?/",
    component: _8b46b5fa,
    pathToRegexpOptions: {"strict":true},
    name: "search-slug___tr"
  }, {
    path: "/tr/suppliers/:slug?/",
    component: _7bab7072,
    pathToRegexpOptions: {"strict":true},
    name: "suppliers-slug___tr"
  }, {
    path: "/vi/account/:page?/",
    component: _12bf1650,
    pathToRegexpOptions: {"strict":true},
    name: "account-page___vi"
  }, {
    path: "/vi/account/:page/",
    component: _12bf1650,
    name: "account___vi"
  }, {
    path: "/vi/account/:page/",
    component: _12bf1650,
    name: "account-orders___vi"
  }, {
    path: "/vi/catalog/:slug?/",
    component: _3a78af00,
    pathToRegexpOptions: {"strict":true},
    name: "catalog-slug___vi"
  }, {
    path: "/vi/docs/:slug/",
    component: _2ff64cd0,
    pathToRegexpOptions: {"strict":true},
    name: "docs-slug___vi"
  }, {
    path: "/vi/events/:slug/",
    component: _570e48f2,
    pathToRegexpOptions: {"strict":true},
    name: "events-slug___vi"
  }, {
    path: "/vi/news/:slug/",
    component: _fbc9d590,
    pathToRegexpOptions: {"strict":true},
    name: "news-slug___vi"
  }, {
    path: "/vi/order-status/:slug?/",
    component: _411aacfa,
    pathToRegexpOptions: {"strict":true},
    name: "order-status-slug___vi"
  }, {
    path: "/vi/products/:slug?/",
    component: _adef24f2,
    pathToRegexpOptions: {"strict":true},
    name: "products-slug___vi"
  }, {
    path: "/vi/promo/:slug?/",
    component: _b6ffebec,
    pathToRegexpOptions: {"strict":true},
    name: "promo-slug___vi"
  }, {
    path: "/vi/search/:slug?/",
    component: _8b46b5fa,
    pathToRegexpOptions: {"strict":true},
    name: "search-slug___vi"
  }, {
    path: "/vi/suppliers/:slug?/",
    component: _7bab7072,
    pathToRegexpOptions: {"strict":true},
    name: "suppliers-slug___vi"
  }, {
    path: "/zh/account/:page?/",
    component: _12bf1650,
    pathToRegexpOptions: {"strict":true},
    name: "account-page___zh"
  }, {
    path: "/zh/account/:page/",
    component: _12bf1650,
    name: "account___zh"
  }, {
    path: "/zh/account/:page/",
    component: _12bf1650,
    name: "account-orders___zh"
  }, {
    path: "/zh/catalog/:slug?/",
    component: _3a78af00,
    pathToRegexpOptions: {"strict":true},
    name: "catalog-slug___zh"
  }, {
    path: "/zh/docs/:slug/",
    component: _2ff64cd0,
    pathToRegexpOptions: {"strict":true},
    name: "docs-slug___zh"
  }, {
    path: "/zh/events/:slug/",
    component: _570e48f2,
    pathToRegexpOptions: {"strict":true},
    name: "events-slug___zh"
  }, {
    path: "/zh/news/:slug/",
    component: _fbc9d590,
    pathToRegexpOptions: {"strict":true},
    name: "news-slug___zh"
  }, {
    path: "/zh/order-status/:slug?/",
    component: _411aacfa,
    pathToRegexpOptions: {"strict":true},
    name: "order-status-slug___zh"
  }, {
    path: "/zh/products/:slug?/",
    component: _adef24f2,
    pathToRegexpOptions: {"strict":true},
    name: "products-slug___zh"
  }, {
    path: "/zh/promo/:slug?/",
    component: _b6ffebec,
    pathToRegexpOptions: {"strict":true},
    name: "promo-slug___zh"
  }, {
    path: "/zh/search/:slug?/",
    component: _8b46b5fa,
    pathToRegexpOptions: {"strict":true},
    name: "search-slug___zh"
  }, {
    path: "/zh/suppliers/:slug?/",
    component: _7bab7072,
    pathToRegexpOptions: {"strict":true},
    name: "suppliers-slug___zh"
  }, {
    path: "/events/year/:year/month/:month/",
    component: _58c4ea3a,
    name: "event-in-month___en"
  }, {
    path: "/account/:page?/",
    component: _12bf1650,
    pathToRegexpOptions: {"strict":true},
    name: "account-page___en"
  }, {
    path: "/account/:page/",
    component: _12bf1650,
    name: "account___en"
  }, {
    path: "/account/:page/",
    component: _12bf1650,
    name: "account-orders___en"
  }, {
    path: "/catalog/:slug?/",
    component: _3a78af00,
    pathToRegexpOptions: {"strict":true},
    name: "catalog-slug___en"
  }, {
    path: "/docs/:slug/",
    component: _2ff64cd0,
    pathToRegexpOptions: {"strict":true},
    name: "docs-slug___en"
  }, {
    path: "/events/:slug/",
    component: _570e48f2,
    pathToRegexpOptions: {"strict":true},
    name: "events-slug___en"
  }, {
    path: "/news/:slug/",
    component: _fbc9d590,
    pathToRegexpOptions: {"strict":true},
    name: "news-slug___en"
  }, {
    path: "/order-status/:slug?/",
    component: _411aacfa,
    pathToRegexpOptions: {"strict":true},
    name: "order-status-slug___en"
  }, {
    path: "/products/:slug?/",
    component: _adef24f2,
    pathToRegexpOptions: {"strict":true},
    name: "products-slug___en"
  }, {
    path: "/promo/:slug?/",
    component: _b6ffebec,
    pathToRegexpOptions: {"strict":true},
    name: "promo-slug___en"
  }, {
    path: "/search/:slug?/",
    component: _8b46b5fa,
    pathToRegexpOptions: {"strict":true},
    name: "search-slug___en"
  }, {
    path: "/suppliers/:slug?/",
    component: _7bab7072,
    pathToRegexpOptions: {"strict":true},
    name: "suppliers-slug___en"
  }, {
    path: "/en/*",
    redirect: "/*"
  }, {
    path: "/",
    component: _b4770d1a,
    pathToRegexpOptions: {"strict":true},
    name: "index___en"
  }],

  fallback: false
}

export function createRouter () {
  return new Router(routerOptions)
}
